### ISSUE TITLE
Algumas divergencias que vi no meu

### ISSUE THREAD

**Issue by abner-serafim** [codeedu/wsl2-docker-quickstart#1]
Boa Noite,

Problemas que passei...

- Nesta parte:

**Habilite o WSL no Windows 10**

**Execute os seguintes comandos no PowerShell em modo administrador:**

**dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart**
**dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart**

após esta parte, tive que reiniciar a cada uma das instalações, pois no meu não funcionou sem reiniciar a cada uma das instalações

para garantir que funcionou abra o power shell e rode **wsl**, se o comando funcionar esta ok

- Essa linha:

**É possível acessar o sistema de arquivos do Linux pela rede do Windows, digite _\wsl$_ no Windows Explorer.** 

tentei de varias formas até entender que é **\\\wsl$** e não **\wsl$**

- caso queiram saber qual versão esta rodando no seu computador, veja essa linha: 

**Execute o comando _wsl -l -v_ com o PowerShell para ver as versões de Linux instaladas e seu status atual(parado ou rodando).**

Esses foram os problemas que passei, que tive alguma dor de cabeça se alguém passar por isso já sabe

Abração

**Comment by argentinaluiz** [comment]
Olá @abner-serafim ,

Obrigado pelo feedback!! Fiz algumas melhorias no tutorial com base no seu feedback.

Se tiver qualquer dúvida, estamos à disposição.
