### ISSUE TITLE
Ubuntu 20.04 - Instalar o Docker com Docker Engine (Docker Nativo) ERRO em sudo apt update

### ISSUE THREAD

**Issue by PauloMussolini** [codeedu/wsl2-docker-quickstart#14]
Comando:
Instale o Docker Engine

sudo apt-get update

Erro:
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Ign:3 https://download.docker.com/linux/ubuntu \ InRelease
Err:4 https://download.docker.com/linux/ubuntu \ Release
  404  Not Found [IP: 13.227.99.78 443]
Hit:5 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Get:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu \ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Como resolver isso ?

**Comment by argentinaluiz** [comment]
Oi @PauloMussolini , tudo bem?

Você está usando a distribuição Ubuntu ou Ubuntu 20.04?

Acredito que o problema tem haver com algo de rede, um proxy ou firewall ativo ou até um antivírus bloqueando.

**Comment by PauloMussolini** [comment]
Boa noite, Luiz.Tudo ótimo e vc?
Eu testei na  Ubuntu18.04 e na na Ubuntu 20.04.O erro é o mesmo.
Acabei de formatar e instalar o win10 Pro. Não configurei nada
Não instalei nenhum antivirus e não uso proxy. Rede doméstica.
Abs
Paulo
    Em terça-feira, 29 de junho de 2021 20:15:06 BRT, Luiz Carlos ***@***.***> escreveu:  
 
 


Oi @PauloMussolini , tudo bem?

Você está usando a distribuição Ubuntu ou Ubuntu 20.04?

Acredito que o problema tem haver com algo de rede, um proxy ou firewall ativo ou até um antivírus bloqueando.

**Comment by argentinaluiz** [comment]
Olá @PauloMussolini , tudo bem?

Conseguiu evoluir com o problema? Realmente isto é estranho, há algum problema com a rede.
Tente usar uma rede que não seja a que você esteja usando ou configurar DNS do Google para evitar problemas nos endereços.

Qualquer dúvida, estou à disposição.

**Comment by Lohn** [comment]
Caro @PauloMussolini 

Creio que nessa parte do guia:

```
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

Você tenha digitado tudo em uma única linha. Aí a barra "\" que é só uma quebra de linha passou a fazer parte do arquivo docker.list.

Podes fazer o seguinte teste? Digita o comando 

`cat /etc/apt/sources.list.d/docker.list`

E o resultado deve ser 

`deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu   focal stable`

A palavra "focal" pode ser diferente se você estiver usando outra versão do ubuntu.

No seu caso deve ter a barra "\" antes da palavra focal, o que provavelmente é a causa do erro.
Para resolver, basta editar o arquivo e removê-la mantendo todo o resto que deve funcionar.

Boa sorte!
