### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by MarceloMileo** [codeedu/wsl2-docker-quickstart#15]
Boa tarde.
Quando executo o docker run, exemplo docker run hello-world, da permission denied

~/live-docker
➜ docker run hello-world
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

**Comment by argentinaluiz** [comment]
Olá @MarceloMileo , tudo bem?

Você fez a instalação do Docker Engine, em vez do Docker Desktop, certo?

No processo de instalação você rodou o comando?

```sh
sudo usermod -aG docker $USER
```

Acredito que o seu usuário está sem permissão para administrar o Docker.

**Comment by MarceloMileo** [comment]
Isso, eu removi toda a instalação do docker desktop e fiz a instalação apenas da docker engine.
Eu executei o
`sudo usermod -aG docker $USER`

**Comment by MarceloMileo** [comment]
@argentinaluiz , talvez  se eu tivesse setado a distro na versão certa funcionaria...hahahahaha
`C:\Users\marcelo.mileo> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         1`

Resolvido a questão, muito obirago pela ajuda.
