### ISSUE TITLE
Adicionar informacao para reiniciar o wsl.

### ISSUE THREAD

**Issue by Jfalca** [codeedu/wsl2-docker-quickstart#16]
Na linha 219 acrecentar essa informação: (não é possivel acessar o docker engine em aplicativo externo se o wsl não for reiniciado)
> 3. Reinicie o WSL (no powershell): `wsl --shutdown`

**Comment by argentinaluiz** [comment]
Olá @Jfalca , tudo bem?

Obrigado pela contribuição. Adicionei esta informação lá.
Pode acontecer que se tenha realmente que reiniciar o WSL, no meu caso por exemplo não precisou.

Grande abraço!
