### ISSUE TITLE
Iniciar docker ao ligar o wsl

### ISSUE THREAD

**Issue by Iraecio** [codeedu/wsl2-docker-quickstart#18]
[Windows 11]

Realizei uns teste para executar o Docker assim que iniciar a maquina, para evitar de sempre estar digitando o comando para iniciar.

Dentro da maquina criei um documento /etc/wsl.conf e coloquei o seguinte comando.

```
[boot]
command="service docker start" 
```

Em seguida sai da instancia e desligue com o comando 

`wsl --shutdown`

E inicie a maquina novamente. e o Docker estará rodando.

**Comment by FernandoGOT** [comment]
Qual windows vc está usando?

Segundo a doc, a sessão `boot` só funciona no windows 11

https://docs.microsoft.com/en-us/windows/wsl/wsl-config#boot-settings

**Comment by Iraecio** [comment]
@FernandoGOT  sim utilizo o Windows 11.

**Comment by argentinaluiz** [comment]
Ótima dica @Iraecio ! No Windows 11 tem-se este recurso no `wsl.conf` para determinar um comando padrão para ser executado no boot o WSL. 

Vou acrescentar isto no tutorial!
