### ISSUE TITLE
Erro ao tentar forçar a atualização

### ISSUE THREAD

**Issue by abner-serafim** [codeedu/wsl2-docker-quickstart#2]
Boa Noite,

Professor tive o problema de não conseguir instalar em meu Notebook, o primeiro problema foi esse do link abaixo e o segundo foi por espaço hehe.

[Nao é possível instalar o windows em um pen drive usando o programa de instalacao](https://answers.microsoft.com/pt-br/windows/forum/all/nao-%C3%A9-poss%C3%ADvel-instalar-o-windows-em-um/ad38f63f-d208-44bb-bf4b-29e5b61d2bdc)

Abraço

**Comment by argentinaluiz** [comment]
Oi @abner-serafim 

Seu pendrive era de quantos gigas?

**Comment by abner-serafim** [comment]
Oi @argentinaluiz 

Professor o erro se da por estar em um notebook com NVME, meu NVME tem 1TB, e mesmo assim deu esses erros, é bizarro.

**Comment by argentinaluiz** [comment]
Olá @abner-serafim 

Este erro com msata II é realmente estranho, o meu também é e não aconteceu isto.

Dê sempre preferência para já fixar a verão 2 antes de instalar a distribuição Linux pela Windows Store.

**Comment by abner-serafim** [comment]
Oi @argentinaluiz 

Então pelo que entendi por ser uma versão de windows do que veio com o computador, por algum motivo esta ativo isso no C para o computador.

Mas pelo menos esse ai é o que eu passei com as configurações de fabrica que veio, acho que se eu instalar um Windows do zero, nunca teria esses problemas.

Abraço
