### ISSUE TITLE
An error  while running the container

### ISSUE THREAD

**Issue by xyhxjw** [codeedu/wsl2-docker-quickstart#20]
I have installed docker on WSL 2, but when i run the container such as hello-world, it is a error about "docker: Error response from daemon: failed to create shim: OCI runtime create failed: systemd cgroup flag passed, but systemd support for managing cgroups is not available: unknown.
ERRO[0000] error waiting for container: context canceled "
![error](https://user-images.githubusercontent.com/49726518/165475596-bfed929d-9424-478a-a24d-7ef580466f39.JPG)

**Comment by argentinaluiz** [comment]
Hi @xyhxjw ,

Which distribution of Linux did you install on Windows with WSL 2? (Ubuntu, Debian e etc).

I see that the terminal is running with root user and it doesn't seem to be in Windows, is that right?

**Comment by mhqmarques** [comment]
The systemd doesn't works in the wsl so you must initiate the docker daemon
manually. In the Debian diatributions you can use service command to do
this.

Marlon Henrique
(31)986131547

Em qua., 27 de abr. de 2022 08:44, Luiz Carlos ***@***.***>
escreveu:
