### ISSUE TITLE
Problemas com o Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by fabriziomachado** [codeedu/wsl2-docker-quickstart#22]
@argentinaluiz ao tentar reproduzir os passos com o Ubuntu 22.04 tive problemas.  Devido ao formato do iptables-nft.
 Consegui contornar com os passos apresentados neste [tutorial](https://crapts.org/2022/05/15/install-docker-in-wsl2-with-ubuntu-22-04-lts/) .

**Comment by thiagosanches** [comment]
Thanks that worked here on Ubuntu 22.04 LTS on WSL 2.0!

**Comment by argentinaluiz** [comment]
Olá @fabriziomachado , tudo bem?

Muito obrigado pelo feedback! Realmente no Ubuntu 22.04 precisa ativar o `iptables-legacy` para resolver o problema de start do serviço do Docker.

Já atualizei o tutorial!

Grande abraço!

**Comment by fellipetav** [comment]
Sugiro alterar o título da issue, por favor. Para quem busca "problemas com o ubuntu ..." é muito genérico.
