### ISSUE TITLE
Dúvida acesso ao Docker em outra máquina

### ISSUE THREAD

**Issue by anderson-lactec** [codeedu/wsl2-docker-quickstart#25]
Não encontrei na documentação nada a respeito.
Tenho instalado no Windows 10 o Docker Engine diretamente instalado no WSL2. 
Tenho um banco de dados instalado no Docker, o Portainer e outro projeto. Gostaria de ter acessar a partir de outra máquina na rede, porém não estou conseguindo.
O que fiz até o momento:
  1. No terminal do Ubuntu, digitei o comando `cat /etc/resolv.conf` para obter o IP. Coloquei o valor no arquivo hosts do Windows;
  2. Instalei o net-tools no Ubuntu, e através do comando ifconfig, obtive o IP da rede eth0. Colei o valor no arquivo hosts do Windows.
  
No hosts, está parecido com isso: `172.17.239.174 wsl.host.local`
Na opção 2, ao digitar no navegador o IP ou wsl.host.local, tenho acesso ao Portainer por exemplo, ou conectar ao banco de dados, porém, ainda não consigo conectar através de outra máquina na mesma rede.

Obrigado

**Comment by igorferreir4** [comment]
Se ainda precisar, talvez isso ajude: https://dev.to/vishnumohanrk/wsl-port-forwarding-2e22
