### ISSUE TITLE
Erro fonte JetBrains Mono

### ISSUE THREAD

**Issue by alexrsg** [codeedu/wsl2-docker-quickstart#27]
Pessoal, no tutorial fala para importarmos o arquivo de configuração do termial.
Importei, mas após abrir o terminal recebo essa mensagem do print anexo.
Como faço para configurar essa fonte?

![image](https://user-images.githubusercontent.com/4266901/210382009-f3f5bd44-5c01-445c-8c0b-b8cc1fa197f5.png)

**Comment by argentinaluiz** [comment]
Olá @alexrsg , tudo bem?

Você baixou um .zip do site da Jet Brains, certo? Neste arquivo tem vários modelos de fonte do JetBrains Mono, qual deles você instalou?

**Comment by alexrsg** [comment]
Oi, @argentinaluiz. Tudo blz.

Baixei o pack de fontes no site da JetBrains e instalei a Regular, Italic, Bold e BoldItalic.
Funcionou certinho!

Vlws

**Comment by argentinaluiz** [comment]
Maravilha @alexrsg ! A fonte padrão é a Regular mesmo.

;)
