### ISSUE TITLE
Erro ao rodar comandos no wsl: /usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by Pitossomo** [codeedu/wsl2-docker-quickstart#28]
Clonei o repositório do projeto BeamsJS do github, mas ao rodar o ```npm install``` recebi a seguinte mensagem:
```/usr/bin/env: ‘bash\r’: No such file or directory```

![image](https://user-images.githubusercontent.com/2355303/216769721-19d1d1d6-dd81-43f6-afe6-99f506ab0aed.png)

Já tentei instalar e reinstalar a imagem, reinstalar o WSL, rodar o Ubuntu 22.04 e o Ubuntu 20.04 mas a mensagem persiste. Isso ocorre com vários outros comandos em todos os projetos. Já no Powershell não tenho problema algum.

**Comment by argentinaluiz** [comment]
Olá @Pitossomo , tudo bem?

Provavelmente isto está acontecendo, porque os projetos estão sendo clonado com Git ou já estavam no Windows e foram copiados para o Linux e tem caracteres estilos Windows enviados na códificação.

Se estiver usando uma ferramenta para clonar projeto, mude o estilo dos caracteres para Linux e se o projeto estiver com algum scripts SH que é executado ao final do `npm install`, instale no Linux o `dos2unix caminho/para/o/sh`.

No link abaixo tem mais informações sobre o estilo de codificação de caracteres com Git:

[https://docs.github.com/pt/get-started/getting-started-with-git/configuring-git-to-handle-line-endings](https://docs.github.com/pt/get-started/getting-started-with-git/configuring-git-to-handle-line-endings).

Me fale se conseguiu evoluir com isto, ok?

;)

**Comment by argentinaluiz** [comment]
Olá @Pitossomo , tudo bem?

Por falta de interação, estou fechando esta issue, a qualquer momento ela pode ser reaberta.
