### ISSUE TITLE
Problema de permissão WSL + Windows

### ISSUE THREAD

**Issue by rafaferreirasantos** [codeedu/wsl2-docker-quickstart#29]
Boa tarde pessoal, estou montando meu ambiente de desenvolvimento com WSL2, mas ao dar um "code ." a partir do terminal do Ubuntu e abrir o VS Code na minha pasta home, mesmo com a extensão do VS Code mostrando que está conectado via WSL, não tenho permissão para editar e nem criar novos arquivos.

Alguém já passou por isso? Sabe como posso resolver?

Obrigado.

https://prnt.sc/qWO3zF36zkqe

**Comment by argentinaluiz** [comment]
Olá @rafaferreirasantos , tudo bem?

Este problema está acontecendo em todos os arquivos do projeto?

Como está na sua pasta de usuário, seu usuário tem permissão irrestrita.

Como este projeto foi gerado no WSL?

Rode o comando 'ls -la .' pra listar os arquivos e a qual usuário ele pertence. Se pertencer a outro usuário, rode o comando 'sudo chown seu_user:seu_user -R .', rode isto na raiz do projeto, vai mudar a propriedade de todos os arquivos para o seu usuário.

Me fale se conseguiu evoluir com isto, ok?

**Comment by rafaferreirasantos** [comment]
Obrigado pelo retorno. Consegui evoluir sim, APARENTEMENTE  (nem sei se isso é possível) mas parece que o Ubuntu foi criado com o WSL (1), removi o Ubuntu, rodei o comando para setar a versão do WSL 2 reinstalei e tudo funcionou sem maiores problemas.... Muito obrigado.

**Comment by argentinaluiz** [comment]
Olá @rafaferreirasantos , tudo bem?

Maravilha, qualquer dúvida, estamos à disposição.
