### ISSUE TITLE
Erro no Ubuntu referente a este código

### ISSUE THREAD

**Issue by Geovanek** [codeedu/wsl2-docker-quickstart#3]
Olá, a parte referente a este trecho de código do arquivo .json de configuração

`{
                "guid": "{73225108-7633-47ae-80c1-5d00111ef647}",
                "hidden": false,
                "name": "Ubuntu",
                "commandline": "C:\\Windows\\System32\\wsl.exe",
                "startingDirectory": "\\\\wsl$\\Ubuntu\\home\\argen\\",
                "icon": "C:\\Program Files\\WindowsApps\\CanonicalGroupLimited.UbuntuonWindows_2004.2020.424.0_x64__79rhkp1fndgsc\\Assets\\Square44x44Logo.altform-unplated_targetsize-256.png"
            },`
da erro na hora de abrir no Windows Terminal : **[processo encerrado com o código 1]**

**Comment by Geovanek** [comment]
Mesmo mudando esta parte **\\\\wsl$\\Ubuntu\\home\\argen\** para meu nome de usuário no ubuntu aparece essa linha descrita acima, o que funciona é o que está o mouse em cima na imagem abaixo.
![Clip2net_200812115132](https://user-images.githubusercontent.com/7670960/90030369-5d7c8900-dc92-11ea-99a0-86b5d6fd552d.png)

**Comment by argentinaluiz** [comment]
Olá @Geovanek ,

A configuração que tem um pinguim abre em /mnt/c/Users/<seu_usuario> e eu quero abrir sempre já dentro do Linux, por isso criei a outra configuração do Ubuntu.

Para corrigir, é necessário ajustar esta parte: **"C:\\Program Files\\WindowsApps\\CanonicalGroupLimited.UbuntuonWindows_2004.2020.424.0_x64__79rhkp1fndgsc\\Assets\\Square44x44Logo.altform-unplated_targetsize-256.png"**

O que muda para cada máquina é o nome do Ubuntu instalado, no meu está **CanonicalGroupLimited.UbuntuonWindows_2004.2020.424.0_x64__79rhkp1fndgsc**, verifique qual é o seu e substitua.

Me dê um feedback sobre isto, ok?

**Comment by Geovanek** [comment]
> Olá @Geovanek ,
> 
> A configuração que tem um pinguim abre em /mnt/c/Users/<seu_usuario> e eu quero abrir sempre já dentro do Linux, por isso criei a outra configuração do Ubuntu.
> 
> Para corrigir, é necessário ajustar esta parte: **"C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_2004.2020.424.0_x64__79rhkp1fndgsc\Assets\Square44x44Logo.altform-unplated_targetsize-256.png"**
> 
> O que muda para cada máquina é o nome do Ubuntu instalado, no meu está **CanonicalGroupLimited.UbuntuonWindows_2004.2020.424.0_x64__79rhkp1fndgsc**, verifique qual é o seu e substitua.
> 
> Me dê um feedback sobre isto, ok?

Olá,
Então, a alteração desta linha é relativa apenas a **Icon** de exibição.

Fui assistir a sua primeira live do assunto [https://www.youtube.com/watch?v=g4HKttouVxA](url) e me liguei que quando dava um wsl -l -v estava como padrão (*) o docker-desktop-data e não o Ubuntu. Fucei nos códigos do wsl e consegui alterar o default e aí começou a funcionar o primeiro Ubuntu que aparece nas opções do Windows Terminal.

Porém, ainda continuava abrindo em /mnt/c/Users/<seu_usuario>.
Aí que percebi que que o erro estava aqui **"startingDirectory": "\\\\wsl$\\Ubuntu_-20.04_\\home\\geovanek\\",**
Tive que alterar para o nome da pasta do meu Ubuntu.

Agora está resolvido.
Apanhando, teimando e apreendendo.
Essa vida de metido a programador por lazer não é fácil.
