### ISSUE TITLE
WSL2 com proxy

### ISSUE THREAD

**Issue by rabelorp** [codeedu/wsl2-docker-quickstart#32]
Você poderia me ajudar com o proxy? Meu git no windows usa um proxy para baixar os arquivos, funciona normalmente. Mas quando vou fazer clone pelo wsl, fica num loop e nunca baixa, trava logo depois do comando. Já configuei .gitconfig no wsl e no windos(está tudo redondo).

Eu tenho que fazer algum tunel através do windows? Será que o firewall está bloqueando a saida do wsl?

**Comment by argentinaluiz** [comment]
Olá @rabelorp , tudo bem?

Consegue compartilhar conosco mais informações sobre o erro que ocorre? Pode ser o texto do log de erro e/ou print do terminal na hora que executou.

Qualquer dúvida, estou à disposição.

;)

**Comment by rabelorp** [comment]
@argentinaluiz antes de mais nada, sou seu fã, seus conteúdos são sensacionais! Vamos lá!

Problema: Não consigo executar nenhum comando GIT no wsl2 e nem conectar aos bancos de dados. Eu segui seu tutorial a risca e tudo funcionou perfeitamente, menos isso. 

Sistema: Windows 10 Pro 21h2 | Wsl2 1.2.5.0 | Docker nativo 23.0.4 | Terminal  ZSH 5.8.1

Obs: Tenho que fazer uso de uma VPN e de um Proxy para poder clonar os repositórios, isso funciona perfeitamente no Windows, mas tenho que ficar usando o GIT Bash.

.gitconfig do windows:
 `[credential "http://proxy.EMPRESA.com.br:9090"]
    provider = generic
[credential "https://repo.EMPRESA-devops.info"]
    provider = generic
[credential "http://EMPRESA-git:8080"]
    provider = generic
[user]
    name = Rabelo
    email = USUARIO_DA_REDE
[http]
    proxy = http://REDE_DA_EMPRESA\\USUARIO@proxy.EMPRESA.com.br:9090
    sslverify = false
[https]
        proxy = https://REDE_DA_EMPRESA\\USUARIO@proxy.EMPRESA.com.br:9090
        sslverify = false
[core]
    autocrlf = false `

.gitconfig no wsl2: o mesmo acima.

/etc/environment: 
`PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
#RABELO
http_proxy="http://REDE_DA_EMPRESA\\USUARIO.terceiro@proxy.EMPRESA.com.br:9090"
https_proxy="http://REDE_DA_EMPRESA\\USUARIO@proxy.EMPRESA.com.br:9090"`

/home/rabelo/.zshrc:
`http_proxy="http://REDE_DA_EMPRESA\\USUARIO.terceiro@proxy.EMPRESA.com.br:9090"
https_proxy="http://REDE_DA_EMPRESA\\USUARIO@proxy.EMPRESA.com.br:9090`

/etc/resolv.config:
`
nameserver IP_PROXY
nameserver IP_BANCO
nameserver 8.8.8.8 // Google
`
Considerações: 
1 - Já tentei usar o Git Credential do Windows e configurar um dentro do WSL2 e nada;
2 - O ping no endereço de proxy funciona;
3 - Já liberei o WSL no Firewall do Windows;

Conforme for lembrando, vou escrevendo aqui. O que você acha que faltou?

**Comment by argentinaluiz** [comment]
Maravilha @rabelorp , obrigado pela contribuição!

A issue servirá para outras pessoas que tiverem este problemas!

Grande abraço!
