### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by claytongf** [codeedu/wsl2-docker-quickstart#35]
Estou tendo problemas com esse erro
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

Segui os passos na instalação dentro do WSL. Quando executo sudo service docker start, recebo OK
Mas quando eu executo um simples docker ps, a mensagem de erro do Docker daemon aparece.

O que mais eu preciso fazer pra funcionar?

PS: tive que instalar desse jeito porque o Docker Desktop tá dando alguns erros de timeout, como por exemplo:
`# wget: bad address 'objects.githubusercontent.com'`
mesmo existindo a url.

Estou usando o Windows 11

**Comment by richellyitalo** [comment]
Tive o mesmo problema. 
Resolvi executando o comando abaixo:
`sudo update-alternatives --config iptables`

Depois informe `1` para o modo legacy

Você pode conferir a raiz do problema conferindo o log
`sudo cat /var/log/docker.log`

**Comment by samuelastech** [comment]
@richellyitalo Sua solução não funcionou para mim.

Também sigo todos os passos de instalação dentro do WSL, configurei o docker para iniciar automaticamente, mas, quando vou rodar o `docker ps` aparece o erro `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`.

Então, tento iniciar o docker manualmente com `sudo service docker start` mas outro erro aparece:

```
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.
```

Alguma ideia de como resolver?
