### ISSUE TITLE
Fazer a instalação e configuração do asdf no wsl2

### ISSUE THREAD

**Issue by fabiocasadossites** [codeedu/wsl2-docker-quickstart#38]
Mestre dos códigos como estão?

Na próxima edição, seria ótimo se pudessem abordar a instalação e configuração do ASDF no WSL2, além de incluir a instalação global de alguns pacotes mais recentes, como, por exemplo:

Java
PHP
Node
Mysql
PostgreSQL

Site oficial: https://asdf-vm.com/
Repositório dos plugins: https://github.com/asdf-vm/asdf-plugins

Um forte abraço !

**Comment by argentinaluiz** [comment]
Oi @fabiocasadossites , tudo bem?

Muito obrigado pelo feedback!

Vou incluir isto nos slides que apresentei na aula: [https://github.com/argentinaluiz/ambiente-dev-produtivo/blob/main/Configura%C3%A7%C3%A3o%20do%20ambiente%20de%20desenvolvimento%20produtivo.pdf](https://github.com/argentinaluiz/ambiente-dev-produtivo/blob/main/Configura%C3%A7%C3%A3o%20do%20ambiente%20de%20desenvolvimento%20produtivo.pdf)

O tutorial de instalar do WSL será mais focado para questões do próprio WSL, já que a instalação do ASDF no WSL é idêntica ao de um Linux convencional!

;)
