### ISSUE TITLE
Another form: Docker Tollbox + WSL 2

### ISSUE THREAD

**Issue by mateushnsoares** [codeedu/wsl2-docker-quickstart#4]
Add this steps in README.md (or show this link) : https://medium.com/@joaoh82/setting-up-docker-toolbox-for-windows-home-10-and-wsl-to-work-perfectly-2fd34ed41d51

**Comment by argentinaluiz** [comment]
Olá @mateushnsoares , tudo bem?

Agora com WSL 2 não é necessário mais usar o Docker Toolbox, pois o WSL 2 é compatível com Windows 10 Home e PRO, e também já está disponível nas builds 20.04, 19.09 e 19.03.

Além do WSL 2 rodar com grande performance quando comparado ao Docker Toolbox.

Entendeu a ideia?
