### ISSUE TITLE
Troca de comando de remoção do Docker

### ISSUE THREAD

**Issue by ThalesAugusto0** [codeedu/wsl2-docker-quickstart#42]
Esse comando não deveria ser substituído por esse aqui.

**ORIGINAL**
```
sudo apt remove docker docker-engine docker.io containerd runc
``` 
**SUGESTÃO**
``` 
sudo apt-get remove docker docker-ce docker-ce-cli docker.io containerd runc
```

já que o nome dos pacotes de atualização do docker mudou

**Comment by argentinaluiz** [comment]
Olá @ThalesAugusto0 , tudo bem?

Muito obrigado pelo contribuição, já fiz a mudança no PR #43 

Grande abraço!
