### ISSUE TITLE
Demora em atualizar codigo no container usando WSL2

### ISSUE THREAD

**Issue by allisonwilliancandido** [codeedu/wsl2-docker-quickstart#49]
Olá pessoal.

Alguém já passou pela seguinta situação?
Estou usando WSL2 com o ubuntu instalado
Dentro do ubuntu tenho o docker e minha aplicação PHP.
Até tudo maravilha, quando executo o compose a pagina é super rapida mas,
a e é que começam o problema.
Quando faço qualquer alteração no meu arquivo do projeto que está no host(ubuntu) demora para atualizar no browser onde estou executando minha aplicação.
Fiz uma media e demora de 1 a 2 minutos para atualizar.
Ex: se alterei somente um texto no meu php fico fazendo varios refresh até que esse novo texto apareça no navegador.

Alguem sabe como contornar isso?

Obrigado.

**Comment by argentinaluiz** [comment]
Olá @allisonwilliancandido , tudo bem?

Isto não é comum. Como está configurado seu ambiente, exemplo, esta aplicação PHP está rodando com servidor WEB embutido do PHP ou está usando Nginx ou Apache? Como é o processo de salvar o arquivo e ele estar disponível para acessar no browser?

**Comment by allisonwilliancandido** [comment]
Estou rodando vários container no compose. Um para o banco, um para o webserver(nginx) e outro para o PHP.
Quando salvo qualquer arquivo .php no host(wsl ubuntu) para persistir essa alteração no container demora mais de 1 minuto.

**Comment by argentinaluiz** [comment]
@allisonwilliancandido , consegue compartilhar um exemplo para testarmos?

**Comment by allisonwilliancandido** [comment]
> @allisonwilliancandido , consegue compartilhar um exemplo para testarmos?

Luiz me desculpe, acabei esquecendo de responder. 
Eu consegui resolver.
Apenas mudei para outra imagem pelo site do dockerhub e funcionou certo agora.
