### ISSUE TITLE
[Atualizar config JSON file]

### ISSUE THREAD

**Issue by eaeniko** [codeedu/wsl2-docker-quickstart#8]
Olá.
Vi que o arquivo de configuração do windows terminal está bem desatualizado, onde o próprio arquivo diz que tem opções novas com melhorias, que poderia ter sido atualizado aqui mesmo.

De qualquer forma eu copiei o arquivo e segui todas as instruções, mas meu por algum motivo, meu terminal fica com essas pastas com fundo verde como se fosse um marca texto, gostaria de saber o que preciso mudar para remover isso, afinal da para ver claramente que é bem ruim de enxergar dessa forma. Não digo da cor do texto e sim essa cor de fundo verde.
![image](https://user-images.githubusercontent.com/20131062/121553236-7d322a00-c9e7-11eb-9665-cbe169d4c9c8.png)

**Comment by argentinaluiz** [comment]
Olá @eaeniko , tudo bem?

Obrigado pelo feedback!

Este arquivo JSON compartilhado é padrão para o Windows Terminal e é validado por JSON Schema, se alguma opção nele estive inválida, o VSCode acusaria.

Já sobre este print que você compartilhou, isto faz parte do próprio tema. As pastas com fundo verde são pastas em que o usuário corrente tem permissão de escrita, já os outros ou são arquivos ou links simbólicos.

Entendeu a ideia?
